spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: sa

    hikari:
      maximumPoolSize: 5
      connectionTimeout: 10000

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true